tractor_trailer_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 20

tractor_trailer_velocity_controller:
  type: tractor_trailer_steering_controller/TractorTrailerSteeringController
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  steer: "base_link__front_cradle_joint"
  fr_wheel_ack_steer: "front_right_ackermann_steering_joint"
  fl_wheel_ack_steer: "front_left_ackermann_steering_joint"
  publish_rate: 10

  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

  cmd_vel_timeout: 0.75
  publish_cmd: True

  wheel_separation: 0.5
  wheel_radius: 0.2
  k_l: 0.1
  k_r: 0.1

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false


  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 10.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.5   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 10.0   # rad/s^2
